var attr = DS.attr;
var belongsTo = DS.belongsTo;
// var hasMany = DS.hasMany;

export default DS.Model.extend({
  uri: attr('string'),
  title: attr('string'),
  artworkUrl: attr('string'),
  attachmentsUri: attr('string'),
  bpm: attr('number'),
  commentCount: attr('number'),
  commentable: attr('boolean'),
  createdAt: attr('date'),
  description: attr('string'),
  downloadCount: attr('number'),
  downloadUrl: attr('string'),
  downloadable: attr('boolean'),
  downloadsRemaining: attr('number'),
  duration: attr('number'),
  embeddableBy: attr('string'),
  favoritingsCount: attr('number'),
  genre: attr('string'),
  isrc: attr('string'),
  keySignature: attr('string'),
  kind: attr('string'),
  labelId: attr('number'),
  labelName: attr('number'),
  license: attr('string'),
  originalContentSize: attr('number'),
  originalFormat: attr('string'),
  permalink: attr('string'),
  permalinkUrl: attr('string'),
  playbackCount: attr('number'),
  purchaseTitle: attr('string'),
  purchaseUrl: attr('string'),
  release: attr('string'),
  releaseDay: attr('number'),
  releaseMonth: attr('number'),
  releaseYear: attr('number'),
  secretToken: attr('string'),
  secretUri: attr('string'),
  sharing: attr('string'),
  state: attr('string'),
  streamUrl: attr('string'),
  streamable: attr('boolean'),
  tagList: attr('string'),
  trackType: attr('string'),
  user: belongsTo('user', { async: true }),
  userFavorite: attr('boolean'),
  userPlaybackCount: attr('number'),
  videoUrl: attr('string'),
  waveformUrl: attr('string')
});
